### ISSUE TITLE
POM to include license

### ISSUE THREAD

**Issue by bp-alex** [client-side/throttle#1]
Thanks for sharing this library! I particularly appreciate its dependency-free footprint and simple API.

Many organisations rely upon licensing management modules to assist them in complying with dependency licenses (eg creating consolidated lists of dependencies, failing builds when an unapproved license is used etc). These modules typically use Maven POM metadata for license information, which is generally quite reliable given Maven Central's deployment staging mechanism enforces a valid (license-including) POM and most Java dependencies are acquired from there. As Throttle is acquired from BinTray and it does not enforce POM metadata, our use of [maven-license-plugin](http://www.mojohaus.org/license-maven-plugin/) currently fails builds that depend on Throttle.

It would help users relying on such modules if you configured Gradle to include the license in your generated POM. I don't use Gradle, so unfortunately I'm not in a position to contribute a pull request. Nevertheless I can point you to [Agrona's Gradle build](https://github.com/real-logic/Agrona/blob/master/build.gradle) which results in a complete POM. A metadata-inclusive POM would also give you the option of deploying to Maven Central (which you can push from BinTray as an aside) and this would perhaps increase visibility and adoption of this highly useful library.

Thanks again for your work on this library and sharing it with the community.

**Comment by jpe42** [comment]
@benalexau, Sorry that I missed this, I must have accidentally deleted the email.  

I think this is a great idea/request.  I didn't know there was tooling around verifying licenses.  I've added the license information to the pom file, you can check it on [Bintray under Files](https://bintray.com/client-side/clients/throttle/0.2.6).  Please let me know if it is written correctly.

Regarding publishing to maven central, if there is a checkbox I can check somewhere within Bintray I will.  Otherwise, figuring out how to publish to maven central was such a nightmare compared to publishing to jcenter I would rather not support that path.

**Comment by bp-alex** [comment]
Thanks for making this change and publishing 0.2.6. I confirm it now works with the aforementioned plugin, for example:

```
# grep throttle ./target/classes/META-INF/projectName-THIRD-PARTY.txt
     (Apache License 2.0) throttle (engineering.clientside:throttle:0.2.6 - https://github.com/client-side/throttle)
```
While we're happy with Throttle being solely on BinTray (we have a repo manager that is configured for BinTray plus other third-party repositories we need), you might wish to deploy to Maven Central to increase discovery and reduce adoption effort (eg I searched Maven Central for "throttle" and "rate limit" and other keywords when I failed to find dependency-free rate limiting libraries via Google). 

If you're interested in doing this https://maven.apache.org/guides/mini/guide-central-repository-upload.html explains the overall process (eg gives a link towards the bottom to create an OSSHR account and Jira ticket) and http://central.sonatype.org/pages/requirements.html goes into more detail about what you would need to add to the POM. Your 0.2.6 POM is very close as far as I can see; you just need a `developers` element and for the `scm` element to include the sub-elements applicable to a Git repo. Once the POM is complete BinTray do the rest already, such as creating JavaDoc and source artifacts, PGP signing all the files etc. The one-click deployment setup is covered in https://bintray.com/docs/usermanual/uploads/uploads_syncingwiththirdpartyplatforms.html#_syncing_artifacts_with_maven_central. I have previously used BinTray and Maven Central pushing worked fine.

Anyhow it's probably half an hour to set all this up and then you can push releases from BinTray to Maven Central with one click going forward. But as I said earlier, those with repo managers don't really need it, so it's really your call re whether the time spent is worthwhile.

Thanks again for adding the license metadata!
