### ISSUE TITLE
ThrottleTest.testStream() failing

### ISSUE THREAD

**Issue by toddobryan** [client-side/throttle#2]
Thanks for this library! Does exactly what I want. Would you consider adding it to Maven? It would make importing it much easier.

I'm having to convert this to my company's package standard, which doesn't use Gradle. When I run the tests, ThrottleTest.testStream() fails. Instead of 1024 acquires taking between 1000 and 1050ms, they're taking 999ms. (I checked the underlying nanoseconds, and it's missing 1000ms by less than 0.5ms--sometimes as little as 0.00001ms.)

I can't get the error to occur using Gradle, but it's fairly consistent with our build system.

Here's the thing, though. Throttle guarantees that the number of permits won't *exceed* the limit, not that it won't meet it, so finishing 1024 acquires in (a very little bit) less than a second is fine. Can I suggest you change the two `IntStream.range(0, qps)` to `IntStream.range(0, qps + 1)` so that really fast computers don't cause an error?

**Comment by jpe42** [comment]
@toddobryan Thanks for the fix suggestion.  Went ahead and added Java 9 module info and released a new version as well.

Regarding maven, it is published to a maven repository.   You just need to add the [Jcenter](https://www.jfrog.com/knowledge-base/why-should-i-use-jcenter-over-maven-central/) repo url (http://jcenter.bintray.com) to your build.

**Comment by bp-alex** [comment]
> Would you consider adding it to Maven? 

Just on this, I provided details in [this comment](https://github.com/client-side/throttle/issues/1#issuecomment-313821007) on how to simplify integration between BinTray and Maven Central if this was of interest to the author. I think most people use a local repository manager these days though and just add BinTray as an additional repo that gets transparently proxied.
